moviebase/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls')),
    path('', include('users.urls')),
]

movies/urls.py
from django.conf.urls.static import static
from django.urls import path
from moviebase import settings
from . import views
from .views import movie_detail, add_movie, kino, serial, anime, multfilm

app_name = 'movies'

urlpatterns = [
    path('', views.home, name='home'),
    path('film/<int:pk>/', movie_detail, name='movie_detail'),
    path('add_movie/', add_movie, name='add_movie'),
    path('kino/', kino, name='kino'),
    path('serial/', serial, name='serial'),
    path('anime/', anime, name='anime'),
    path('multfilm/', multfilm, name='multfilm'),
    path('about/', views.about, name='about'),
    path('movie/<int:movie_id>/like_dislike/', views.like_dislike_movie, name='like_dislike'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, LogoutView, ProfileView,EditProfileView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit', EditProfileView.as_view(), name='edit-profile'),

]

movies/models.py
from django.db import models

from users.models import CustomUser


class Movie(models.Model):
    CATEGORY_CHOICES = [
        ('kino', 'Kino'),
        ('anime', 'Anime'),
        ('serial', 'Serial'),
        ('multfilm', 'Multfilm'),
    ]

    title = models.CharField(max_length=200)
    description = models.TextField()
    year = models.IntegerField()
    country = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    director = models.CharField(max_length=100)
    actors = models.CharField(max_length=300)
    rating = models.FloatField()
    duration = models.CharField(max_length=20)
    age_limit = models.CharField(max_length=10)

    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    poster = models.ImageField(upload_to='posters/')
    trailer_link = models.URLField(blank=True, null=True)
    video_file = models.FileField(upload_to='movies/', blank=True, null=True)
    video_link = models.URLField(blank=True, null=True)
    def __str__(self):
        return self.title


class LikeDislike(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    action = models.CharField(max_length=10, choices=[('like', 'Like'), ('dislike', 'Dislike')])

    class Meta:
        unique_together = ('user', 'movie')  # Ensures a user can only like/dislike a movie once

class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='reviews')
    user_name = models.CharField(max_length=100)
    rating = models.FloatField()
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Review by {self.user_name} for {self.movie.title}'
from django.db import models

class Celebrity(models.Model):
    name = models.CharField(max_length=100)  # Mashhur shaxsning ismi
    image = models.ImageField(upload_to='celebrities/')  # Rasmni saqlash joyi
    rating = models.DecimalField(max_digits=2, decimal_places=1, default=0)  # Reyting, masalan 4.5
    bio = models.TextField(blank=True)  # Biografiya (ixtiyoriy)

    def __str__(self):
        return self.name

movies/forms.py
from django import forms
from .models import Movie, Review

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = [
            'title', 'description', 'year', 'country', 'genre', 'director',
            'actors', 'rating', 'duration', 'age_limit', 'category', 'poster', 'trailer_link'
        ]

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['user_name', 'rating', 'comment']

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Review, Celebrity
from .forms import MovieForm, ReviewForm

# Create your views here.
from django.shortcuts import render
from .models import Movie


# views.py
from django.shortcuts import get_object_or_404, redirect

def like_dislike_movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    if request.method == 'POST':
        action = request.POST.get('action')
        if action == 'like':
            movie.likes_count += 1
        elif action == 'dislike':
            movie.dislikes_count += 1
        movie.save()
    return redirect('movies:movie_detail', pk=movie.pk)
def home(request):

    celebrities = Celebrity.objects.all()
    latest_movies = Movie.objects.order_by('-id')[:5]
    star_range = range(1, 6)
    movies = Movie.objects.all()
    search = request.GET.get('q')
    if search:
        movies = Movie.objects.filter(title__icontains=search)
    else:
        movies = Movie.objects.all()


    categories = ['anime', 'kino', 'serial', 'multfilm']
    categorized_movies = {category: movies.filter(category=category) for category in categories}

        # Har bir kategoriya uchun 3 tadan guruhlash
    for category, movie_list in categorized_movies.items():
        categorized_movies[category] = [movie_list[i:i + 3] for i in range(0, len(movie_list), 3)]

    context = {
            'celebrities': celebrities,
            'latest_movies': latest_movies,
            'categorized_movies': categorized_movies,
            'star_range': star_range,
            'movies': movies,
    }



    return render(request, 'home.html', context)


def movie_detail(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    reviews = movie.reviews.all()

    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.movie = movie
            review.save()
            return redirect('movies:movie_detail', pk=movie.pk)
    else:
        review_form = ReviewForm()

    return render(request, 'movie_detail.html', {
        'movie': movie,
        'reviews': reviews,
        'review_form': review_form,
    })
def add_movie(request):
    if request.user.is_superuser:
        if request.method == "POST":
            form = MovieForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return redirect('movies:home')
        else:
            form = MovieForm()
        return render(request, 'add-movie.html', {'form': form})
    else:
        return redirect('movies:home')



def kino(request):
    movies = Movie.objects.filter(category='kino')
    return render(request, 'kino.html', {'movies': movies})

def serial(request):
    movies = Movie.objects.filter(category='serial')
    return render(request, 'serial.html', {'movies': movies})

def anime(request):
    movies = Movie.objects.filter(category='anime')
    return render(request, 'anime.html', {'movies': movies})

def multfilm(request):
    movies = Movie.objects.filter(category='multfilm')
    return render(request, 'multfilm.html', {'movies': movies})

def about(request):
    return render(request,'about.html')

movies/templates/about.html
{% extends 'base.html' %}

{% block title %}Bu sayt haqida{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-8 offset-md-2 mb-5">
        <h1 class="text-center my-4">Sayt haqida</h1>

        <h3>Maqsadimiz</h3>
        <p>Ushbu sayt kino, anime, serial va multfilm ixlosmandlari uchun bir joyda sifatli kontentni to‘plash va ularga qulay ko‘rish imkoniyatini berishni maqsad qiladi.</p>

        <h3>Saytdagi bo‘limlar</h3>
        <ul>
            <li><strong>Kinolar:</strong> Eng yangi va klassik filmlar.</li>
            <li><strong>Anime:</strong> Dunyodagi mashhur anime seriyalari.</li>
            <li><strong>Seriallar:</strong> Ko‘plab tanilgan va yangi seriallar.</li>
            <li><strong>Multfilmlar:</strong> Bolalar va kattalar uchun mo‘ljallangan multfilmlar.</li>
        </ul>

        <h3>Foydalanish qo‘llanmasi</h3>
        <p>Ro‘yxatdan o‘ting va login qiling. Shundan so‘ng, barcha kinolar va seriallarni ko‘rish imkoniyatiga ega bo‘lasiz. Sevimli kontentingizni qidiruv orqali toping va baholang.</p>

        <h3>Yangiliklar</h3>
        <p>Tez orada saytga yangi funksiya – tomosha tarixini saqlash va kino tavsiyalarini olish imkoniyati qo‘shiladi.</p>

        <h3>Aloqa</h3>
        <p>Agar sayt haqida fikr yoki takliflaringiz bo‘lsa, biz bilan bog‘laning:</p>
        <ul>
            <li>Email: admin@kinobase.com</li>
            <li>Instagram: <a href="#">@kinobase</a></li>
            <li>Telegram: <a href="#">@kinobase_official</a></li>
        </ul>

        <h3>Sayt muallifi</h3>
        <p>Ushbu loyiha <strong>Israiljanov Behruz</strong> tomonidan yaratilgan va <em>IT Park Python Django amaliyot kursi</em> doirasida ishlab chiqilgan.</p>

        <h3>Statistika</h3>
        <ul>
            <li>100+ film katalogga kiritilgan</li>
            <li>500+ foydalanuvchi ro‘yxatdan o‘tgan</li>
            <li>Har oy 1000+ tomosha amalga oshiriladi</li>
        </ul>
    </div>
</div>
{% endblock %}

movies/templates/add-movie.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Film Qo'shish{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-3">

    <h1>Yangi Film Qo'shish</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary" > Saqlash </button>
    </form>
    </div>
    </div>
</div>
{% endblock %}

movies/templates/anime.html
{% extends 'base.html' %}

{% block title %}Anime{% endblock %}

{% block content %}
 {% if request.user.is_authenticated %}

<h2 class="text-center my-4">Anime</h2>

<div class="container my-3">
    <div class="row row-cols-1 row-cols-md-3 row-cols-lg-6 g-3">
        {% for movie in movies %}
            {% if movie.category == 'anime' %}
                <div class="col p-1">
                    <a href="{% url 'movies:movie_detail' movie.pk %}" style="text-decoration: none; color: inherit;">
                        <div class="card h-70">
                            <img src="{{ movie.poster.url }}"
                                 class="card-img-top"
                                 alt="{{ movie.title }}"
                                 style="width: 100%; height: 300px; object-fit: cover;">
                            <div class="card-body">
                                <h5 class="card-title text-center">{{ movie.title }}</h5>
                                <div class="d-flex justify-content-center my-1">
                                    {% for i in "12345" %}
                                        <span>⭐</span>
                                    {% endfor %}
                                </div>
                                <p class="card-text text-center mb-1">{{ movie.year }}</p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endif %}
        {% endfor %}
          {% else %}
    <div class="text-center my-5">
        <h1>Bu menyuni ko'rish uchun avval <a href="{% url 'users:login' %}?next={% url 'movies:anime' %}">login</a> qiling.</h1>
    </div>
         {% endif %}
    </div>
</div>
{% endblock %}

movies/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}"> <!-- CSS faylini qo'shish -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js">
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <title>{% block title %}Kinobase{% endblock %}</title>
  <script src="{% static 'js/js.js' %}"></script>
</head>

<body class="bg-dark text-white">
  <nav class="navbar navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Kinobase</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
          <span class="navbar-toggler-icon"></span>
      </button>

      <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex flex-row">

        <li class="nav-item mx-2">

          <a class="nav-link active" aria-current="page" href="{% url 'movies:home' %}">Home</a>
        </li>
        <li class="nav-item mx-2">
          <a class="nav-link active" aria-current="page" href="{% url 'movies:kino' %}">Kino</a>
        </li>
        <li class="nav-item mx-2">
          <a class="nav-link active" aria-current="page" href="{% url 'movies:serial' %}">Serial</a>
        </li>
        <li class="nav-item mx-2">
          <a class="nav-link active" aria-current="page" href="{% url 'movies:anime' %}">Anime</a>
        </li>
        <li class="nav-item mx-2">
          <a class="nav-link active" aria-current="page" href="{% url 'movies:multfilm' %}">Multfilm</a>
        </li>
      </ul>

      <form class="d-flex" role="search" action="{% url 'movies:home' %}">
        <input class="form-control me-2 bg-light text-dark" type="search" placeholder="Search" aria-label="Search" name="q" >
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </nav>

  <div class="offcanvas offcanvas-end bg-dark text-white" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
      <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">

        {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{ request.user.username }}
            </a>
            <ul class="dropdown-menu bg-dark text-white">
              <li><a class="dropdown-item bg-dark text-white" href="{% url 'users:profile' %}">Profile</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item bg-dark text-white" href="{% url 'users:logout' %}">Logout</a></li>
            </ul>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="btn btn-primary me-5" href="{% url 'users:login' %}">Login</a>
          </li>
        {% endif %}
        <li class="nav-link" >
          <a class="dropdown-item text-white "  href="{% url 'movies:about' %}" >Sayt haqida</a>
        </ul>
        {% if user.is_superuser %}
        <li class="nav-item">
          <a href="{% url 'movies:add_movie' %}" class="btn btn-success">Film Qo'shish</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
  {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
  <div class="container mt-5 pt-5">
    {% block content %}
    {% endblock %}
  </div>
</body>

</html>

movies/templates/kino.html
{% extends 'base.html' %}

{% block title %}Kino{% endblock %}

{% block content %}

 {% if request.user.is_authenticated %}
<h2 class="text-center my-4">Kino</h2>

<div class="container my-3">
    <div class="row row-cols-1 row-cols-md-3 row-cols-lg-6 g-3">
        {% for movie in movies %}
            {% if movie.category == 'kino' %}
                <div class="col p-1">
                    <a href="{% url 'movies:movie_detail' movie.pk %}" style="text-decoration: none; color: inherit;">
                        <div class="card h-70">
                            <img src="{{ movie.poster.url }}"
                                 class="card-img-top"
                                 alt="{{ movie.title }}"
                                 style="width: 100%; height: 300px; object-fit: cover;">
                            <div class="card-body">
                                <h5 class="card-title text-center">{{ movie.title }}</h5>
                                <div class="d-flex justify-content-center my-1">
                                    {% for i in "12345" %}
                                        <span>⭐</span>
                                    {% endfor %}
                                </div>
                                <p class="card-text text-center mb-1">{{ movie.year }}</p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endif %}
        {% endfor %}
       {% else %}
    <div class="text-center my-5">
        <h1>Bu menyuni ko'rish uchun avval <a href="{% url 'users:login' %}?next={% url 'movies:kino' %}">login</a> qiling.</h1>
    </div>
         {% endif %}
    </div>
</div>
{% endblock %}

movies/templates/movie_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}{{ movie.title }}{% endblock %}

{% block content %}
{% if request.user.is_authenticated %}

<div class="row">
    <div class="col-2">
        <div class="movie-detail">
            <img style="width: 210px; height: 300px;" src="{{ movie.poster.url }}" alt="{{ movie.title }}">
            <!-- Star Rating Display -->
            <div class="rating mt-2 text-center">
                {% for i in "12345" %}
                    {% if movie.rating|floatformat:1 >= i %}
                        <span class="fa fa-star checked" style="color: gold;"></span>
                    {% else %}
                        <span class="fa fa-star"></span>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="col-7">
        <h1>{{ movie.title }}</h1>
        <p><strong>Yili:</strong> {{ movie.year }}</p>
        <p><strong>Davlati:</strong> {{ movie.country }}</p>
        <p><strong>Janr:</strong> {{ movie.genre }}</p>
        <p><strong>Rejissor:</strong> {{ movie.director }}</p>
        <p><strong>Aktyorlar:</strong> {{ movie.actors }}</p>
        <p><strong>Reyting:</strong> {{ movie.rating }}</p>
        <p><strong>Davomiyligi:</strong> {{ movie.duration }}</p>
        <p><strong>Yosh chegarasi:</strong> {{ movie.age_limit }}</p>
        <p><strong>Tavsif:</strong> {{ movie.description }}</p>
        <a href="{{ movie.trailer_link }}" target="_blank">Trailer</a>

 {% if request.user.is_authenticated %}
    <div class="like-dislike mt-3">
        <form method="post" action="{% url 'movies:like_dislike' movie.pk %}">
            {% csrf_token %}
            {% if not movie.likes_count == 0 and movie.dislikes_count == 0 %}
                <button type="submit" name="action" value="like" class="btn btn-success" {% if movie.likes_count %} disabled {% endif %}>
                    👍  (<span>{{ movie.likes_count }}</span>)
                </button>
                <button type="submit" name="action" value="dislike" class="btn btn-danger ms-2" {% if movie.dislikes_count %} disabled {% endif %}>
                    👎  (<span>{{ movie.dislikes_count }}</span>)
                </button>

            {% endif %}
        </form>
    </div>
{% endif %}


    </div>
</div>

{% if movie.video_link %}
    <div style="margin-top: 20px;">
        <iframe width="640" height="360" src="{{ movie.video_link }}" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
    </div>
{% elif movie.video_file %}
    <video controls width="640" height="360">
        <source src="{{ movie.video_file.url }}" type="video/mp4">
        Sizning brauzeringiz videoni qo‘llab-quvvatlamaydi.
    </video>
{% else %}
    <p>Video mavjud emas.</p>
{% endif %}

<h2 class="mt-4">Izohlar</h2>
{% for review in reviews %}
  <div class="row mb-3">
      <div class="col-3">
        <strong>{{ review.user_name }}</strong>
        (Rating: {{ review.rating }})
        <p>{{ review.comment }}</p>
        <p><small>{{ review.created_at }}</small></p>
    </div>
{% empty %}
    <p>Bu filmga hali hech kim izoh qoldirmagan.</p>
{% endfor %}

<div class="row mb-3">
    <div class="col-3">
        <h3 class="mt-4">Yangi izoh qo'shish</h3>
        <form method="post">
            {% csrf_token %}
            {{ review_form|crispy }}
            <button type="submit" class="btn btn-primary mt-2">Qo'shish</button>
        </form>
    </div>
</div>

{% else %}
<div class="text-center my-5">
    <h1>Anime, Kino, Serial, Multfimlar ko'rish uchun avval <a href="{% url 'users:login' %}?next={% url 'movies:kino' %}">login</a> qiling.</h1>
</div>
{% endif %}
{% endblock %}

movies/templates/multfilm.html
{% extends 'base.html' %}

{% block title %}Multfilmlar{% endblock %}

{% block content %}
 {% if request.user.is_authenticated %}

<h2 class="text-center my-4">Multfilmlar</h2>

<div class="container my-3">
    <div class="row row-cols-1 row-cols-md-3 row-cols-lg-6 g-3">
        {% for movie in movies %}
            {% if movie.category == 'multfilm' %}
                <div class="col p-1">
                    <a href="{% url 'movies:movie_detail' movie.pk %}" style="text-decoration: none; color: inherit;">
                        <div class="card h-70">
                            <img src="{{ movie.poster.url }}"
                                 class="card-img-top"
                                 alt="{{ movie.title }}"
                                 style="width: 100%; height: 300px; object-fit: cover;">
                            <div class="card-body">
                                <h5 class="card-title text-center">{{ movie.title }}</h5>
                                <div class="d-flex justify-content-center my-1">
                                    {% for i in "12345" %}
                                        <span>⭐</span>
                                    {% endfor %}
                                </div>
                                <p class="card-text text-center mb-1">{{ movie.year }}</p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endif %}
        {% endfor %}
         {% else %}
    <div class="text-center my-5">
        <h1>Bu menyuni ko'rish uchun avval <a href="{% url 'users:login' %}?next={% url 'movies:multfilm' %}">login</a> qiling.</h1>
    </div>
         {% endif %}
    </div>
</div>
{% endblock %}

movies/templates/serial.html
{% extends 'base.html' %}

{% block title %}Serial{% endblock %}

{% block content %}
 {% if request.user.is_authenticated %}

<h2 class="text-center my-4">Serial</h2>

<div class="container my-3">
    <div class="row row-cols-1 row-cols-md-3 row-cols-lg-6 g-3">
        {% for movie in movies %}
            {% if movie.category == 'serial' %}
                <div class="col p-1">
                    <a href="{% url 'movies:movie_detail' movie.pk %}" style="text-decoration: none; color: inherit;">
                        <div class="card h-70">
                            <img src="{{ movie.poster.url }}"
                                 class="card-img-top"
                                 alt="{{ movie.title }}"
                                 style="width: 100%; height: 300px; object-fit: cover;">
                            <div class="card-body">
                                <h5 class="card-title text-center">{{ movie.title }}</h5>
                                <div class="d-flex justify-content-center my-1">
                                    {% for i in "12345" %}
                                        <span>⭐</span>
                                    {% endfor %}
                                </div>
                                <p class="card-text text-center mb-1">{{ movie.year }}</p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endif %}
        {% endfor %}
          {% else %}
    <div class="text-center my-5">
        <h1>Bu menyuni ko'rish uchun avval <a href="{% url 'users:login' %}?next={% url 'movies:serial' %}">login</a> qiling.</h1>
    </div>
         {% endif %}
    </div>
</div>
{% endblock %}